//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class egreso
    {
        public long id { get; set; }
        public System.DateTime fecha { get; set; }
        public string tratamiento { get; set; }
        public decimal monto { get; set; }
        public bool borrado { get; set; }
        public long medicoid { get; set; }
        public long ingresoid { get; set; }
        public long pacienteid { get; set; }
    
        public virtual ingreso ingreso { get; set; }
        public virtual medico medico { get; set; }
        public virtual paciente paciente { get; set; }
    }
}
