//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingreso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ingreso()
        {
            this.egreso = new HashSet<egreso>();
        }
    
        public long id { get; set; }
        public System.DateTime fecha { get; set; }
        public int numerosala { get; set; }
        public int numerocama { get; set; }
        public string diagnostico { get; set; }
        public string observacion { get; set; }
        public bool borrado { get; set; }
        public long medicoid { get; set; }
        public long pacienteid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<egreso> egreso { get; set; }
        public virtual medico medico { get; set; }
        public virtual paciente paciente { get; set; }
    }
}
