//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace modelo.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class medico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public medico()
        {
            this.egreso = new HashSet<egreso>();
            this.ingreso = new HashSet<ingreso>();
        }
    
        public long id { get; set; }
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string apellidopat { get; set; }
        public string apellidomat { get; set; }
        public bool esespecialista { get; set; }
        public bool habilitado { get; set; }
        public bool borrado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<egreso> egreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ingreso> ingreso { get; set; }
    }
}
